# Generated by Django 5.1.5 on 2025-02-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('friend', 'Amigo'), ('enemy', 'Enemigo'), ('ally', 'Aliado'), ('rival', 'Rival'), ('neutral', 'Neutral')], default='neutral', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('character1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships1', to='juego.character')),
                ('character2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships2', to='juego.character')),
            ],
            options={
                'unique_together': {('character1', 'character2')},
            },
        ),
    ]
