# Generated by Django 5.1.5 on 2025-02-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='description',
        ),
    ]
