# Generated by Django 5.1.5 on 2025-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_remove_relationship_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='critic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
