# Generated by Django 5.1.5 on 2025-02-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0004_weapon_accuracy_weapon_critic'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='image',
            field=models.ImageField(blank=True, default='armors/default_armor.jpg', null=True, upload_to='armors/'),
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, default='characters/default_character.jpg', null=True, upload_to='characters/'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='image',
            field=models.ImageField(blank=True, default='weapons/default_weapon.jpg', null=True, upload_to='weapons/'),
        ),
    ]
